# Generated by Django 5.2.8 on 2025-11-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('attendance', models.CharField(blank=True, choices=[('yes', 'Yes, I will attend'), ('no', 'No, I cannot attend')], max_length=10, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('vip_token', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
