# Generated by Django 5.2.8 on 2025-11-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='song_request_for_dj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
