# Generated by Django 5.2.8 on 2025-11-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weddingmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingmedia',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
